# Generated by Django 4.2.27 on 2025-12-29 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('fbs_a', models.CharField(max_length=50)),
                ('fbs_b', models.CharField(max_length=100)),
                ('stock_bno', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StockRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(max_length=20)),
                ('stock_name', models.CharField(blank=True, max_length=100)),
                ('date', models.DateField()),
                ('buy_volume', models.IntegerField(default=0)),
                ('sell_volume', models.IntegerField(default=0)),
                ('net_volume', models.IntegerField(default=0)),
                ('record_type', models.IntegerField(default=1)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='links.broker')),
            ],
            options={
                'unique_together': {('broker', 'stock_code', 'date', 'record_type')},
            },
        ),
    ]
